// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBG: typeof import('./src/components/AppBG.vue')['default']
    AppEditor: typeof import('./src/components/AppEditor.vue')['default']
    AppUpload: typeof import('./src/components/AppUpload.vue')['default']
  }
}
